CREATE TABLE PATIENT(
  PATIENT_ID INT PRIMARY KEY,
  PATIENT_NAME VARCHAR(50),
  PATIENT_AGE INT,
  PATIENT_EMAIL_ID VARCHAR(50),
  PATIENT_PHONE_NUMBER VARCHAR(20),
  PATIENT_GENDER VARCHAR(40)
);

INSERT INTO PATIENT VALUES(1,'MANISH',21,'manishmyadavmanishm@gmail.com','8095081666','MALE');
INSERT INTO PATIENT 
VALUES (2, 'Rahul', 25, 'rahul@gmail.com', '9876543210', 'MALE');
INSERT INTO PATIENT
VALUES (3, 'Priya', 22, 'priya@gmail.com', '9876543211', 'FEMALE');

INSERT INTO PATIENT
VALUES (4, 'Arjun', 30, 'arjun@gmail.com', '9876543212', 'MALE');

INSERT INTO PATIENT
VALUES (5, 'Sneha', 28, 'sneha@gmail.com', '9876543213', 'FEMALE');

INSERT INTO PATIENT
VALUES (6, 'Kiran', 35, 'kiran@gmail.com', '9876543214', 'MALE');

INSERT INTO PATIENT
VALUES (7, 'Anjali', 24, 'anjali@gmail.com', '9876543215', 'FEMALE');

INSERT INTO PATIENT
VALUES (8, 'Ravi', 40, 'ravi@gmail.com', '9876543216', 'MALE');

INSERT INTO PATIENT
VALUES (9, 'Pooja', 27, 'pooja@gmail.com', '9876543217', 'FEMALE');

INSERT INTO PATIENT
VALUES (10, 'Vikram', 33, 'vikram@gmail.com', '9876543218', 'MALE');

CREATE TABLE DOCTOR(
  DOCTOR_ID INT,
  DOCTOR_NAME VARCHAR(40),
  DOCTOR_SPELIZATION VARCHAR(40),
  DOCTOR_GENDER VARCHAR(20)
);

INSERT INTO DOCTOR
VALUES (101, 'Dr. Rajesh', 'Cardiologist', 'MALE');

INSERT INTO DOCTOR
VALUES (102, 'Dr. Arjun', 'Cardiologist', 'MALE');

INSERT INTO DOCTOR
VALUES (103, 'Dr. Priya', 'Cardiologist', 'FEMALE');

INSERT INTO DOCTOR
VALUES (104, 'Dr. Ravi', 'Cardiologist', 'MALE');

INSERT INTO DOCTOR
VALUES (105, 'Dr. Sneha', 'Dermatologist', 'FEMALE');

INSERT INTO DOCTOR
VALUES (106, 'Dr. Kiran', 'Neurologist', 'MALE');

INSERT INTO DOCTOR
VALUES (107, 'Dr. Anjali', 'Pediatrician', 'FEMALE');

INSERT INTO DOCTOR
VALUES (108, 'Dr. Vikram', 'Orthopedic', 'MALE');

INSERT INTO DOCTOR
VALUES (109, 'Dr. Meera', 'Gynecologist', 'FEMALE');

INSERT INTO DOCTOR
VALUES (110, 'Dr. Pooja', 'ENT Specialist', 'FEMALE');

CREATE TABLE APPOINTMENT(
  PATIENT_ID INT ,
  DOCTOR_ID INT,
  APPOINTEMENT_ID INT PRIMARY KEY,
  APPOINTEMENT_DATE VARCHAR(20),
  APPOINTEMENT_TIME VARCHAR(20)
);
INSERT INTO APPOINTMENT
VALUES (1, 101, 1001, '08-06-2026', '09:00 AM');

INSERT INTO APPOINTMENT
VALUES (2, 102, 1002, '09-06-2026', '10:00 AM');

INSERT INTO APPOINTMENT
VALUES (3, 103, 1003, '10-06-2026', '11:00 AM');

INSERT INTO APPOINTMENT
VALUES (4, 104, 1004, '11-06-2026', '12:00 PM');

INSERT INTO APPOINTMENT
VALUES (5, 105, 1005, '12-06-2026', '02:00 PM');

INSERT INTO APPOINTMENT
VALUES (6, 106, 1006, '13-06-2026', '03:00 PM');

INSERT INTO APPOINTMENT
VALUES (7, 107, 1007, '14-06-2026', '09:30 AM');

INSERT INTO APPOINTMENT
VALUES (8, 108, 1008, '15-06-2026', '10:30 AM');

INSERT INTO APPOINTMENT
VALUES (9, 109, 1009, '16-06-2026', '11:30 AM');

INSERT INTO APPOINTMENT
VALUES (10, 110, 1010, '17-06-2026', '01:00 PM');

CREATE TABLE BILLING(
  PATIENT_ID INT ,
  BILLING_ID INT PRIMARY KEY,
  TOTAL_BILLING_AMMOUNT DECIMAL,
  APPOINTEMENT_ID INT,
  MEDICAL_CHARGE INT
);
INSERT INTO BILLING VALUES (1, 2001, 1500, 1001,  500);

INSERT INTO BILLING VALUES (2, 2002, 1800, 1002,  600);

INSERT INTO BILLING VALUES (3, 2003, 2100, 1003, 700);

INSERT INTO BILLING VALUES (4, 2004, 2400, 1004,  800);

INSERT INTO BILLING VALUES (5, 2005, 2600, 1005,  900);

INSERT INTO BILLING VALUES (6, 2006, 2800, 1006,  1000);

INSERT INTO BILLING VALUES (7, 2007, 3000, 1007,  1100);

INSERT INTO BILLING VALUES (8, 2008, 3300, 1008,  1200);

INSERT INTO BILLING VALUES (9, 2009, 3600, 1009,  1300);

INSERT INTO BILLING VALUES (10, 2010, 4000, 1010,  1500);

CREATE TABLE DEPARTEMENT(
DOCTOR_ID INT,
DEPRTEMENT_SPELIZATION VARCHAR(45)
);
INSERT INTO DEPARTEMENT
VALUES (101,  'Cardiology');

INSERT INTO DEPARTEMENT
VALUES (102, 'Cardiology');

INSERT INTO DEPARTEMENT
VALUES (103,  'Cardiology');

INSERT INTO DEPARTEMENT
VALUES (104,  'Cardiology');

INSERT INTO DEPARTEMENT
VALUES (105,  'Dermatology');

INSERT INTO DEPARTEMENT
VALUES (106,  'Neurology');

INSERT INTO DEPARTEMENT
VALUES (107,  'Pediatrics');

INSERT INTO DEPARTEMENT
VALUES (108,  'Orthopedics');

INSERT INTO DEPARTEMENT
VALUES (109, 'Gynecology');

INSERT INTO DEPARTEMENT
VALUES (110, 'ENT');

CREATE TABLE SALARY(
  DOCTOR_ID INT,
  INITIAL_AMMOUNT FLOAT,
  BONOUS_AMOUNT FLOAT,
  TOTAL_SALARY FLOAT
);
INSERT INTO SALARY
VALUES (101, 50000, 5000, 55000);

INSERT INTO SALARY
VALUES (102, 52000, 6000, 58000);

INSERT INTO SALARY
VALUES (103, 55000, 7000, 62000);

INSERT INTO SALARY
VALUES (104, 58000, 8000, 66000);

INSERT INTO SALARY
VALUES (105, 60000, 9000, 69000);

INSERT INTO SALARY
VALUES (106, 62000, 10000, 72000);

INSERT INTO SALARY
VALUES (107, 65000, 11000, 76000);

INSERT INTO SALARY
VALUES (108, 68000, 12000, 80000);

INSERT INTO SALARY
VALUES (109, 70000, 13000, 83000);

INSERT INTO SALARY
VALUES (110, 75000, 15000, 90000);
SET LINESIZE 200;
SET PAGESIZE 50;
COLUMN PATIENT_NAME FORMAT A30;
SELECT* FROM PATIENT;
SET LINESIZE 250;
SET PAGESIZE 80;
COLUMN PATIENT_NAME FORMAT A300;
SELECT * FROM DOCTOR;
SELECT*FROM BILLING;

SELECT PATIENT_ID,PATIENT_NAME,PATIENT_GENDER
FROM PATIENT 
WHERE PATIENT_ID = 6 AND PATIENT_GENDER='MALE';

SELECT PATIENT_ID,PATIENT_NAME,PATIENT_GENDER
FROM PATIENT 
WHERE PATIENT_ID = 7 AND PATIENT_GENDER ='FEMALE';

SELECT PATIENT_NAME,PATIENT_AGE
FROM PATIENT
WHERE PATIENT_AGE>33;

SELECT DOCTOR_ID, MAX(TOTAL_SALARY) AS TOTAL_MAX_SALARY
FROM SALARY
WHERE TOTAL_SALARY >58000
GROUP BY DOCTOR_ID
ORDER BY MAX(TOTAL_SALARY) DESC;

SELECT PATIENT_ID,PATIENT_AGE,PATIENT_NAME
FROM PATIENT
WHERE PATIENT_AGE>21;


SELECT SUM(TOTAL_SALARY)AS TOTAL_SALARY
FROM SALARY;


SELECT DISTINCT DOCTOR_SPELIZATION
FROM DOCTOR ;

SELECT COUNT(*) AS NO_OF_PATIENT
FROM PATIENT;

ALTER TABLE PATIENT
MODIFY PATIENT_NAME VARCHAR(30) NOT NULL;
INSERT INTO PATIENT VALUES (11, NULL, 25,'antorojas@gmail.com','9164331739','MALE');
INSERT INTO PATIENT VALUES (12 ,NULL, 18,'rajesh123@gmail.com','9620692858','MALE');

ALTER TABLE DOCTOR
ADD CONSTRAINT PRE_KEY PRIMARY KEY(DOCTOR_ID);
INSERT INTO DOCTOR
VALUES (111, 'Dr.RAM', 'Cardiologist', 'Male');

INSERT INTO DOCTOR
VALUES (112, 'Dr. VIKRAM', 'Cardiologist', 'Male');

ALTER TABLE  APPOINTMENT ADD CONSTRAINT FRG_KEY FOREIGN KEY(PATIENT_ID)
REFERENCES PATIENT(PATIENT_ID);

ALTER TABLE  APPOINTMENT  ADD CONSTRAINT FRG_APPOINTEMENT FOREIGN KEY(DOCTOR_ID)
REFERENCES  DOCTOR(DOCTOR_ID);

ALTER TABLE BILLING ADD CONSTRAINT FRG_BILLING FOREIGN KEY(PATIENT_ID)
REFERENCES PATIENT(PATIENT_ID);

ALTER TABLE DEPARTEMENT ADD CONSTRAINT FRG_DEPARTEMENT FOREIGN KEY(DOCTOR_ID)
REFERENCES  DOCTOR(DOCTOR_ID);

ALTER TABLE SALARY ADD CONSTRAINT FRG_SALARY FOREIGN KEY(DOCTOR_ID)
REFERENCES  DOCTOR(DOCTOR_ID);

ALTER TABLE PATIENT
ADD CONSTRAINT UNI_CF UNIQUE(PATIENT_EMAIL_ID);
INSERT INTO PATIENT
VALUES (15, 'JYOTHI', 40, 'arjun@gmail.com', '9876543212', 'Male');

INSERT INTO PATIENT
VALUES (19, 'NANDHINI', 35, 'sneha@gmail.com', '9876543213', 'Female');

ALTER TABLE PATIENT
ADD CONSTRAINT CHEC_UF CHECK(PATIENT_AGE>18);

INSERT INTO PATIENT
VALUES (3, 'RAMYA', 30, 'ramya@gmail.com', '9876543212', 'Male');

INSERT INTO PATIENT
VALUES (4, 'SOMYA', 15, 'sneha@gmail.com', '9876543213', 'Female');

ALTER TABLE DOCTOR
ENABLE CONSTRAINT PRE_KEY;
INSERT INTO DOCTOR VALUES(111, 'Dr.RAM', 'Cardiologist', 'Male');

ALTER TABLE DOCTOR
ENABLE CONSTRAINT PRE_KEY;
INSERT INTO DOCTOR VALUES(111, 'Dr.RAM', 'Cardiologist', 'Male');

 SELECT * 
FROM(
  SELECT DOCTOR_ID,TOTAL_SALARY
  FROM SALARY
  ORDER BY TOTAL_SALARY DESC
)
WHERE ROWNUM<5;

UPDATE SALARY
SET TOTAL_SALARY=TOTAL_SALARY+1000
WHERE DOCTOR_ID=105;

SELECT S.PATIENT_ID,S.PATIENT_NAME
FROM PATIENT S
FULL OUTER JOIN  APPOINTMENT C 
ON C .PATIENT_ID=S.PATIENT_ID;

SELECT D.DOCTOR_ID,D.DOCTOR_NAME
FROM DOCTOR D
FULL OUTER JOIN   APPOINTMENT E 
ON E .DOCTOR_ID = D.DOCTOR_ID;

SELECT D.DOCTOR_ID,D.DOCTOR_NAME,U.TOTAL_SALARY
FROM DOCTOR  D
FULL OUTER JOIN SALARY U
ON U.DOCTOR_ID = D.DOCTOR_ID;

CREATE INDEX INDX_EMPO
ON PATIENT(PATIENT_NAME);

SELECT *
FROM PATIENT
WHERE PATIENT_NAME='MANISH';

CREATE UNIQUE INDEX INDX_RFG
ON PATIENT(PATIENT_EMAIL_ID);

SELECT *
FROM PATIENT
WHERE PATIENT_EMAIL_ID ='manishmyadavmanishm@gmail.com';

SELECT *
FROM PATIENT
WHERE PATIENT_EMAIL_ID ='vikram@gmail.com';


CREATE INDEX IDX_DOCTOR_ID_DOCTOR_SPELIZATION
ON DOCTOR(DOCTOR_ID,DOCTOR_SPELIZATION);

SELECT DOCTOR_ID,DOCTOR_SPELIZATION
FROM DOCTOR 
WHERE DOCTOR_ID=103 AND DOCTOR_SPELIZATION='Cardiologist';

DROP INDEX IDX_DOCTOR_ID_DOCTOR_SPELIZATION;

CREATE VIEW PATIENT_V4 AS
SELECT PATIENT_ID,PATIENT_NAME
FROM PATIENT
WHERE PATIENT_ID=6;

SELECT * FROM PATIENT_V4;

CREATE VIEW PATIENT_DETAIL AS
SELECT S.PATIENT_ID,S.PATIENT_NAME
FROM PATIENT S
FULL OUTER JOIN APPOINTMENT C
ON C.PATIENT_ID=S.PATIENT_ID;

SELECT * FROM PATIENT_DETAIL;

CREATE VIEW SALARY_DATA AS
SELECT DOCTOR_ID, TOTAL_SALARY
FROM SALARY 
WHERE TOTAL_SALARY > 62000
WITH READ ONLY;

SELECT * FROM SALARY_DATA ;

DROP VIEW SALARY_DATA;

SELECT * FROM SALARY_DATA;

CREATE TABLE AUDIT_TABLE(
  USER_NAME VARCHAR(20),
  ACTION_PERFORMED VARCHAR(20),
  ACTION_TIME DATE 
);
CREATE TRIGGER  APPOINTMENT_TRIGGER
BEFORE INSERT ON  APPOINTMENT
FOR EACH ROW
BEGIN
  INSERT INTO AUDIT_TABLE VALUES('USER','INSERT',SYSDATE);
END;
/
INSERT INTO  APPOINTMENT VALUES(1, 101, 10001, '20-08-2025', '12:00 AM');
COMMIT;

SELECT * FROM AUDIT_TABLE;
SELECT * FROM APPOINTMENT;